# Generated by Django 4.2 on 2023-06-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alamatpengiriman',
            name='alamat_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alamatpengiriman',
            name='alamat_2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alamatpengiriman',
            name='negara',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('T', 'Tops'), ('P', 'Pants'), ('SC', 'Scraf')], max_length=2),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='nama_produk',
            field=models.CharField(max_length=10),
        ),
    ]
